// Catálogo editable. Los títulos son rótulos curatoriales del sitio, no títulos oficiales.
// Reemplaza archivos/rutas al recibir las fotos nuevas. Copia las futureSlots completas a photos y publica con published: true.
// Las fotos entregadas por el cliente usan provenance: "client", source vacío y provisional: false.
// WhatsApp: identificador para wa.me, sin espacios; no usar como formato de tel:.
window.ALEXA_SITE = {
  "instagram": "https://www.instagram.com/aleroblesfotografia/",
  "whatsapp": "5216121044559",
  "email": "alexalarar17@gmail.com",
  "photos": [
    {
      "id": "client-eb564a12cb2ba25d",
      "title": "La luz sobre ti",
      "category": "retratos",
      "alt": "Retrato de una mujer junto al mar, iluminada por la luz cálida del atardecer",
      "src": "assets/portfolio/client-eb564a12cb2ba25d-800.webp",
      "full": "assets/portfolio/client-eb564a12cb2ba25d-1600.webp",
      "width": 800,
      "height": 533,
      "srcWidth": 800,
      "fullWidth": 1600,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-31ef8e0be15acc42",
      "title": "Junto a la ventana",
      "category": "editorial",
      "alt": "Retrato editorial de una mujer con sombrero, pantalón de mezclilla y botas, sentada junto a una ventana",
      "src": "assets/portfolio/client-31ef8e0be15acc42-800.webp",
      "full": "assets/portfolio/client-31ef8e0be15acc42-1600.webp",
      "width": 551,
      "height": 800,
      "srcWidth": 551,
      "fullWidth": 1032,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-dda36444dea92a62",
      "title": "Texturas en negro",
      "category": "producto",
      "alt": "Abrigo negro con cuello de textura suave colgado en una percha al aire libre",
      "src": "assets/portfolio/client-dda36444dea92a62-800.webp",
      "full": "assets/portfolio/client-dda36444dea92a62-1600.webp",
      "width": 509,
      "height": 800,
      "srcWidth": 509,
      "fullWidth": 815,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-ef8e6eae51b8005e",
      "title": "Al caer la tarde",
      "category": "exteriores",
      "alt": "Retrato de una mujer con las manos cerca del rostro junto a la playa al atardecer",
      "src": "assets/portfolio/client-ef8e6eae51b8005e-800.webp",
      "full": "assets/portfolio/client-ef8e6eae51b8005e-1600.webp",
      "width": 528,
      "height": 800,
      "srcWidth": 528,
      "fullWidth": 1057,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-fe0e54cb54c35a27",
      "title": "Entre madera y sombra",
      "category": "editorial",
      "alt": "Retrato editorial de una mujer sentada en escalones de madera, con chaqueta negra, jeans y botas",
      "src": "assets/portfolio/client-fe0e54cb54c35a27-800.webp",
      "full": "assets/portfolio/client-fe0e54cb54c35a27-1600.webp",
      "width": 546,
      "height": 800,
      "srcWidth": 546,
      "fullWidth": 1013,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-9f39881809abc738",
      "title": "Cada paso",
      "category": "producto",
      "alt": "Detalle de botas negras de tacón y pantalón de mezclilla sobre escalones de madera",
      "src": "assets/portfolio/client-9f39881809abc738-800.webp",
      "full": "assets/portfolio/client-9f39881809abc738-1600.webp",
      "width": 800,
      "height": 533,
      "srcWidth": 800,
      "fullWidth": 1280,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-317deed13d63c35f",
      "title": "Entre luces suaves",
      "category": "retratos",
      "alt": "Mujer de espaldas mirando a cámara con una prenda estampada, rodeada de plantas y madera",
      "src": "assets/portfolio/client-317deed13d63c35f-800.webp",
      "full": "assets/portfolio/client-317deed13d63c35f-1600.webp",
      "width": 484,
      "height": 800,
      "srcWidth": 484,
      "fullWidth": 775,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-3b2595626fbf508d",
      "title": "Los detalles cuentan",
      "category": "producto",
      "alt": "Detalle de jeans y botas negras en una composición de moda sobre una silla de madera",
      "src": "assets/portfolio/client-3b2595626fbf508d-800.webp",
      "full": "assets/portfolio/client-3b2595626fbf508d-1600.webp",
      "width": 800,
      "height": 640,
      "srcWidth": 800,
      "fullWidth": 1280,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-c6ce56d54bcea129",
      "title": "Una actitud propia",
      "category": "editorial",
      "alt": "Mujer sentada en una silla de madera con sombrero oscuro y vestuario de inspiración western",
      "src": "assets/portfolio/client-c6ce56d54bcea129-800.webp",
      "full": "assets/portfolio/client-c6ce56d54bcea129-1600.webp",
      "width": 584,
      "height": 800,
      "srcWidth": 584,
      "fullWidth": 1013,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "client-6adccfb9dd6283d8",
      "title": "Prendas con carácter",
      "category": "producto",
      "alt": "Detalle de una prenda estampada sostenida junto a jeans y botas negras",
      "src": "assets/portfolio/client-6adccfb9dd6283d8-800.webp",
      "full": "assets/portfolio/client-6adccfb9dd6283d8-1600.webp",
      "width": 533,
      "height": 800,
      "srcWidth": 533,
      "fullWidth": 853,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "0a3d2d576f16a487",
      "title": "Frente al mar",
      "category": "retratos",
      "alt": "Retrato en blanco y negro de un hombre con abrigo junto al mar",
      "src": "assets/instagram/0a3d2d576f16a487-800.webp",
      "full": "assets/instagram/0a3d2d576f16a487-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1080,
      "position": "50% 50%",
      "source": "https://www.instagram.com/irvingdelreall/p/Dc6p0tRD5nt/",
      "provisional": true,
      "published": true
    },
    {
      "id": "client-0e241686bc2190ec",
      "title": "La última luz",
      "category": "exteriores",
      "alt": "Mujer en la orilla de la playa bajo la luz dorada del atardecer",
      "src": "assets/portfolio/client-0e241686bc2190ec-800.webp",
      "full": "assets/portfolio/client-0e241686bc2190ec-1600.webp",
      "width": 601,
      "height": 800,
      "srcWidth": 601,
      "fullWidth": 1203,
      "position": "50% 50%",
      "source": "",
      "provenance": "client",
      "provisional": false,
      "published": true
    },
    {
      "id": "10c82cf5bf288652",
      "title": "Rojo, presente",
      "category": "familia",
      "alt": "Retrato de maternidad en estudio con vestido y guantes rojos",
      "src": "assets/instagram/10c82cf5bf288652-800.webp",
      "full": "assets/instagram/10c82cf5bf288652-1600.webp",
      "width": 615,
      "height": 800,
      "srcWidth": 615,
      "fullWidth": 1231,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLN2eKAAM9/",
      "provisional": true,
      "published": true
    },
    {
      "id": "e157d921d65da218",
      "title": "Entre palmeras",
      "category": "exteriores",
      "alt": "Retrato de una mujer bajo una palapa rodeada de vegetación tropical",
      "src": "assets/instagram/e157d921d65da218-800.webp",
      "full": "assets/instagram/e157d921d65da218-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Dbgx1E9kvB-/",
      "provisional": true,
      "published": true
    },
    {
      "id": "bb3c353e9091c7e7",
      "title": "Nostalgia",
      "category": "retratos",
      "alt": "Hombre de abrigo negro mirando hacia el mar en una costa rocosa",
      "src": "assets/instagram/bb3c353e9091c7e7-800.webp",
      "full": "assets/instagram/bb3c353e9091c7e7-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXiHB-Rjy3p/",
      "provisional": true,
      "published": true
    },
    {
      "id": "4431622a34d5865a",
      "title": "Luz y color",
      "category": "editorial",
      "alt": "Retrato creativo en estudio con iluminación rosa y violeta",
      "src": "assets/instagram/4431622a34d5865a-800.webp",
      "full": "assets/instagram/4431622a34d5865a-1600.webp",
      "width": 800,
      "height": 562,
      "srcWidth": 800,
      "fullWidth": 1440,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXHqPWFAIZP/",
      "provisional": true,
      "published": true
    },
    {
      "id": "abb1679d8750678b",
      "title": "Un nuevo capítulo",
      "category": "familia",
      "alt": "Pareja abrazada durante una celebración de maternidad",
      "src": "assets/instagram/abb1679d8750678b-800.webp",
      "full": "assets/instagram/abb1679d8750678b-1600.webp",
      "width": 800,
      "height": 622,
      "srcWidth": 800,
      "fullWidth": 994,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DYpciKjlJnk/",
      "provisional": true,
      "published": true
    },
    {
      "id": "98a263d5b57e57c3",
      "title": "Entre sombras",
      "category": "editorial",
      "alt": "Retrato de mujer con vestido negro de encaje en estudio",
      "src": "assets/instagram/98a263d5b57e57c3-800.webp",
      "full": "assets/instagram/98a263d5b57e57c3-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXD4V2LAMSE/",
      "provisional": true,
      "published": true
    },
    {
      "id": "c965def67e654d88",
      "title": "A cielo abierto",
      "category": "exteriores",
      "alt": "Retrato de una excursionista sobre una formación rocosa bajo el cielo azul",
      "src": "assets/instagram/c965def67e654d88-800.webp",
      "full": "assets/instagram/c965def67e654d88-1600.webp",
      "width": 800,
      "height": 603,
      "srcWidth": 800,
      "fullWidth": 1600,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DX-NvQiEmox/",
      "provisional": true,
      "published": true
    },
    {
      "id": "0691c1a207ac7375",
      "title": "A su manera",
      "category": "retratos",
      "alt": "Mujer sentada en un sillón con vestuario de estampado y pantalón blanco",
      "src": "assets/instagram/0691c1a207ac7375-800.webp",
      "full": "assets/instagram/0691c1a207ac7375-1600.webp",
      "width": 638,
      "height": 800,
      "srcWidth": 638,
      "fullWidth": 1276,
      "position": "50% 50%",
      "source": "https://www.instagram.com/milelaraaa/p/DbMtOZZFLrI/",
      "provisional": true,
      "published": true
    },
    {
      "id": "9aa063c3e68a3861",
      "title": "La espera",
      "category": "familia",
      "alt": "Retrato de maternidad con vestido blanco y flores al fondo",
      "src": "assets/instagram/9aa063c3e68a3861-800.webp",
      "full": "assets/instagram/9aa063c3e68a3861-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 900,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DYpcY_tFG6Q/",
      "provisional": true,
      "published": true
    },
    {
      "id": "255fd6bd7f635925",
      "title": "Tiempo lento",
      "category": "exteriores",
      "alt": "Hombre sentado en una mesa al aire libre en Bodegas de Santo Tomás",
      "src": "assets/instagram/255fd6bd7f635925-800.webp",
      "full": "assets/instagram/255fd6bd7f635925-1600.webp",
      "width": 800,
      "height": 587,
      "srcWidth": 800,
      "fullWidth": 940,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXyD-PRlWe-/",
      "provisional": true,
      "published": true
    },
    {
      "id": "2d306aeaa0b33a09",
      "title": "Sin prisa",
      "category": "exteriores",
      "alt": "Retrato de mujer junto a un árbol y una cerca de madera",
      "src": "assets/instagram/2d306aeaa0b33a09-800.webp",
      "full": "assets/instagram/2d306aeaa0b33a09-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Db6l_b5kt1l/",
      "provisional": true,
      "published": true
    },
    {
      "id": "6cabff2f988ded5c",
      "title": "Ecos",
      "category": "editorial",
      "alt": "Composición fotográfica con varias exposiciones de un hombre entre rocas",
      "src": "assets/instagram/6cabff2f988ded5c-800.webp",
      "full": "assets/instagram/6cabff2f988ded5c-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DZG5n_nAAVn/",
      "provisional": true,
      "published": true
    },
    {
      "id": "d08e6106fdd95ec7",
      "title": "Una nueva vida",
      "category": "familia",
      "alt": "Retrato de maternidad con vestido rojo largo frente a un fondo de estudio",
      "src": "assets/instagram/d08e6106fdd95ec7-800.webp",
      "full": "assets/instagram/d08e6106fdd95ec7-1600.webp",
      "width": 691,
      "height": 800,
      "srcWidth": 691,
      "fullWidth": 1381,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLNAxJADXL/",
      "provisional": true,
      "published": true
    },
    {
      "id": "11c49497e4ca7481",
      "title": "Instante suspendido",
      "category": "retratos",
      "alt": "Retrato de hombre con abrigo negro frente a una cerca de madera",
      "src": "assets/instagram/11c49497e4ca7481-800.webp",
      "full": "assets/instagram/11c49497e4ca7481-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXr9p8hD4Q_/",
      "provisional": true,
      "published": true
    },
    {
      "id": "8b625b9792ab5155",
      "title": "Otra frecuencia",
      "category": "editorial",
      "alt": "Retrato de cuerpo completo con camisa blanca y luz rosa de estudio",
      "src": "assets/instagram/8b625b9792ab5155-800.webp",
      "full": "assets/instagram/8b625b9792ab5155-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXIQ7UrjwRp/",
      "provisional": true,
      "published": true
    },
    {
      "id": "49cf888a65a9afb9",
      "title": "Entre ramas",
      "category": "exteriores",
      "alt": "Composición con retrato de mujer entre árboles, con marco blanco original",
      "src": "assets/instagram/49cf888a65a9afb9-800.webp",
      "full": "assets/instagram/49cf888a65a9afb9-1600.webp",
      "width": 625,
      "height": 800,
      "srcWidth": 625,
      "fullWidth": 1170,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Da05AKSjzT2/",
      "provisional": true,
      "published": true
    },
    {
      "id": "54f9e2d30528cc74",
      "title": "Intensidad",
      "category": "familia",
      "alt": "Retrato de maternidad en vestido rojo, sentada sobre escalones de estudio",
      "src": "assets/instagram/54f9e2d30528cc74-800.webp",
      "full": "assets/instagram/54f9e2d30528cc74-1600.webp",
      "width": 645,
      "height": 800,
      "srcWidth": 645,
      "fullWidth": 1290,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLNDZcgKPH/",
      "provisional": true,
      "published": true
    },
    {
      "id": "f40f779fcb570e0a",
      "title": "Pequeño universo",
      "category": "familia",
      "alt": "Retrato de una bebé con diadema roja en una sesión al aire libre",
      "src": "assets/instagram/f40f779fcb570e0a-800.webp",
      "full": "assets/instagram/f40f779fcb570e0a-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXzuwHYj-O6/",
      "provisional": true,
      "published": true
    },
    {
      "id": "4fc2231295549ac1",
      "title": "En movimiento",
      "category": "editorial",
      "alt": "Sesión creativa con luces rosa y violeta y pose sobre una superficie reflectante",
      "src": "assets/instagram/4fc2231295549ac1-800.webp",
      "full": "assets/instagram/4fc2231295549ac1-1600.webp",
      "width": 786,
      "height": 800,
      "srcWidth": 786,
      "fullWidth": 1440,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXHsgowgGDO/",
      "provisional": true,
      "published": true
    },
    {
      "id": "10ba6964bfd55850",
      "title": "Dirección y luz",
      "category": "editorial",
      "alt": "Retrato de mujer con vestido negro sentada en estudio",
      "src": "assets/instagram/10ba6964bfd55850-800.webp",
      "full": "assets/instagram/10ba6964bfd55850-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXD4RLXgK7y/",
      "provisional": true,
      "published": true
    }
  ],
  "futureSlots": [
    {
      "id": "nueva-serie-01",
      "title": "",
      "category": "retratos",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-02",
      "title": "",
      "category": "editorial",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-03",
      "title": "",
      "category": "familia",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-04",
      "title": "",
      "category": "exteriores",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-05",
      "title": "",
      "category": "retratos",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-06",
      "title": "",
      "category": "editorial",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    }
  ]
};
