// Catálogo editable. Los títulos son rótulos curatoriales del sitio, no títulos oficiales.
// Reemplaza archivos/rutas al recibir las fotos nuevas. Copia las futureSlots completas a photos y publica con published: true.
// WhatsApp: código de país + número, sin espacios. Vacío = consulta por el Instagram oficial.
window.ALEXA_SITE = {
  "instagram": "https://www.instagram.com/aleroblesfotografia/",
  "whatsapp": "",
  "photos": [
    {
      "id": "0a3d2d576f16a487",
      "title": "Frente al mar",
      "category": "retratos",
      "alt": "Retrato en blanco y negro de un hombre con abrigo junto al mar",
      "src": "assets/instagram/0a3d2d576f16a487-800.webp",
      "full": "assets/instagram/0a3d2d576f16a487-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1080,
      "position": "50% 50%",
      "source": "https://www.instagram.com/irvingdelreall/p/Dc6p0tRD5nt/",
      "provisional": true,
      "published": true
    },
    {
      "id": "6c7baf05c3cd4e0c",
      "title": "La última luz",
      "category": "exteriores",
      "alt": "Mujer en la orilla de la playa bajo la luz dorada del atardecer",
      "src": "assets/instagram/6c7baf05c3cd4e0c-800.webp",
      "full": "assets/instagram/6c7baf05c3cd4e0c-1600.webp",
      "width": 601,
      "height": 800,
      "srcWidth": 601,
      "fullWidth": 1202,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Dc6q2hODyyx/",
      "provisional": true,
      "published": true
    },
    {
      "id": "10c82cf5bf288652",
      "title": "Rojo, presente",
      "category": "familia",
      "alt": "Retrato de maternidad en estudio con vestido y guantes rojos",
      "src": "assets/instagram/10c82cf5bf288652-800.webp",
      "full": "assets/instagram/10c82cf5bf288652-1600.webp",
      "width": 615,
      "height": 800,
      "srcWidth": 615,
      "fullWidth": 1231,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLN2eKAAM9/",
      "provisional": true,
      "published": true
    },
    {
      "id": "e157d921d65da218",
      "title": "Entre palmeras",
      "category": "exteriores",
      "alt": "Retrato de una mujer bajo una palapa rodeada de vegetación tropical",
      "src": "assets/instagram/e157d921d65da218-800.webp",
      "full": "assets/instagram/e157d921d65da218-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Dbgx1E9kvB-/",
      "provisional": true,
      "published": true
    },
    {
      "id": "bb3c353e9091c7e7",
      "title": "Nostalgia",
      "category": "retratos",
      "alt": "Hombre de abrigo negro mirando hacia el mar en una costa rocosa",
      "src": "assets/instagram/bb3c353e9091c7e7-800.webp",
      "full": "assets/instagram/bb3c353e9091c7e7-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXiHB-Rjy3p/",
      "provisional": true,
      "published": true
    },
    {
      "id": "4431622a34d5865a",
      "title": "Luz y color",
      "category": "editorial",
      "alt": "Retrato creativo en estudio con iluminación rosa y violeta",
      "src": "assets/instagram/4431622a34d5865a-800.webp",
      "full": "assets/instagram/4431622a34d5865a-1600.webp",
      "width": 800,
      "height": 562,
      "srcWidth": 800,
      "fullWidth": 1440,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXHqPWFAIZP/",
      "provisional": true,
      "published": true
    },
    {
      "id": "abb1679d8750678b",
      "title": "Un nuevo capítulo",
      "category": "familia",
      "alt": "Pareja abrazada durante una celebración de maternidad",
      "src": "assets/instagram/abb1679d8750678b-800.webp",
      "full": "assets/instagram/abb1679d8750678b-1600.webp",
      "width": 800,
      "height": 622,
      "srcWidth": 800,
      "fullWidth": 994,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DYpciKjlJnk/",
      "provisional": true,
      "published": true
    },
    {
      "id": "98a263d5b57e57c3",
      "title": "Entre sombras",
      "category": "editorial",
      "alt": "Retrato de mujer con vestido negro de encaje en estudio",
      "src": "assets/instagram/98a263d5b57e57c3-800.webp",
      "full": "assets/instagram/98a263d5b57e57c3-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXD4V2LAMSE/",
      "provisional": true,
      "published": true
    },
    {
      "id": "c965def67e654d88",
      "title": "A cielo abierto",
      "category": "exteriores",
      "alt": "Retrato de una excursionista sobre una formación rocosa bajo el cielo azul",
      "src": "assets/instagram/c965def67e654d88-800.webp",
      "full": "assets/instagram/c965def67e654d88-1600.webp",
      "width": 800,
      "height": 603,
      "srcWidth": 800,
      "fullWidth": 1600,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DX-NvQiEmox/",
      "provisional": true,
      "published": true
    },
    {
      "id": "0691c1a207ac7375",
      "title": "A su manera",
      "category": "retratos",
      "alt": "Mujer sentada en un sillón con vestuario de estampado y pantalón blanco",
      "src": "assets/instagram/0691c1a207ac7375-800.webp",
      "full": "assets/instagram/0691c1a207ac7375-1600.webp",
      "width": 638,
      "height": 800,
      "srcWidth": 638,
      "fullWidth": 1276,
      "position": "50% 50%",
      "source": "https://www.instagram.com/milelaraaa/p/DbMtOZZFLrI/",
      "provisional": true,
      "published": true
    },
    {
      "id": "9aa063c3e68a3861",
      "title": "La espera",
      "category": "familia",
      "alt": "Retrato de maternidad con vestido blanco y flores al fondo",
      "src": "assets/instagram/9aa063c3e68a3861-800.webp",
      "full": "assets/instagram/9aa063c3e68a3861-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 900,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DYpcY_tFG6Q/",
      "provisional": true,
      "published": true
    },
    {
      "id": "255fd6bd7f635925",
      "title": "Tiempo lento",
      "category": "exteriores",
      "alt": "Hombre sentado en una mesa al aire libre en Bodegas de Santo Tomás",
      "src": "assets/instagram/255fd6bd7f635925-800.webp",
      "full": "assets/instagram/255fd6bd7f635925-1600.webp",
      "width": 800,
      "height": 587,
      "srcWidth": 800,
      "fullWidth": 940,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXyD-PRlWe-/",
      "provisional": true,
      "published": true
    },
    {
      "id": "2d306aeaa0b33a09",
      "title": "Sin prisa",
      "category": "exteriores",
      "alt": "Retrato de mujer junto a un árbol y una cerca de madera",
      "src": "assets/instagram/2d306aeaa0b33a09-800.webp",
      "full": "assets/instagram/2d306aeaa0b33a09-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Db6l_b5kt1l/",
      "provisional": true,
      "published": true
    },
    {
      "id": "6cabff2f988ded5c",
      "title": "Ecos",
      "category": "editorial",
      "alt": "Composición fotográfica con varias exposiciones de un hombre entre rocas",
      "src": "assets/instagram/6cabff2f988ded5c-800.webp",
      "full": "assets/instagram/6cabff2f988ded5c-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DZG5n_nAAVn/",
      "provisional": true,
      "published": true
    },
    {
      "id": "d08e6106fdd95ec7",
      "title": "Una nueva vida",
      "category": "familia",
      "alt": "Retrato de maternidad con vestido rojo largo frente a un fondo de estudio",
      "src": "assets/instagram/d08e6106fdd95ec7-800.webp",
      "full": "assets/instagram/d08e6106fdd95ec7-1600.webp",
      "width": 691,
      "height": 800,
      "srcWidth": 691,
      "fullWidth": 1381,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLNAxJADXL/",
      "provisional": true,
      "published": true
    },
    {
      "id": "11c49497e4ca7481",
      "title": "Instante suspendido",
      "category": "retratos",
      "alt": "Retrato de hombre con abrigo negro frente a una cerca de madera",
      "src": "assets/instagram/11c49497e4ca7481-800.webp",
      "full": "assets/instagram/11c49497e4ca7481-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXr9p8hD4Q_/",
      "provisional": true,
      "published": true
    },
    {
      "id": "8b625b9792ab5155",
      "title": "Otra frecuencia",
      "category": "editorial",
      "alt": "Retrato de cuerpo completo con camisa blanca y luz rosa de estudio",
      "src": "assets/instagram/8b625b9792ab5155-800.webp",
      "full": "assets/instagram/8b625b9792ab5155-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXIQ7UrjwRp/",
      "provisional": true,
      "published": true
    },
    {
      "id": "49cf888a65a9afb9",
      "title": "Entre ramas",
      "category": "exteriores",
      "alt": "Composición con retrato de mujer entre árboles, con marco blanco original",
      "src": "assets/instagram/49cf888a65a9afb9-800.webp",
      "full": "assets/instagram/49cf888a65a9afb9-1600.webp",
      "width": 625,
      "height": 800,
      "srcWidth": 625,
      "fullWidth": 1170,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/Da05AKSjzT2/",
      "provisional": true,
      "published": true
    },
    {
      "id": "54f9e2d30528cc74",
      "title": "Intensidad",
      "category": "familia",
      "alt": "Retrato de maternidad en vestido rojo, sentada sobre escalones de estudio",
      "src": "assets/instagram/54f9e2d30528cc74-800.webp",
      "full": "assets/instagram/54f9e2d30528cc74-1600.webp",
      "width": 645,
      "height": 800,
      "srcWidth": 645,
      "fullWidth": 1290,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXLNDZcgKPH/",
      "provisional": true,
      "published": true
    },
    {
      "id": "f40f779fcb570e0a",
      "title": "Pequeño universo",
      "category": "familia",
      "alt": "Retrato de una bebé con diadema roja en una sesión al aire libre",
      "src": "assets/instagram/f40f779fcb570e0a-800.webp",
      "full": "assets/instagram/f40f779fcb570e0a-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXzuwHYj-O6/",
      "provisional": true,
      "published": true
    },
    {
      "id": "4fc2231295549ac1",
      "title": "En movimiento",
      "category": "editorial",
      "alt": "Sesión creativa con luces rosa y violeta y pose sobre una superficie reflectante",
      "src": "assets/instagram/4fc2231295549ac1-800.webp",
      "full": "assets/instagram/4fc2231295549ac1-1600.webp",
      "width": 786,
      "height": 800,
      "srcWidth": 786,
      "fullWidth": 1440,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXHsgowgGDO/",
      "provisional": true,
      "published": true
    },
    {
      "id": "10ba6964bfd55850",
      "title": "Dirección y luz",
      "category": "editorial",
      "alt": "Retrato de mujer con vestido negro sentada en estudio",
      "src": "assets/instagram/10ba6964bfd55850-800.webp",
      "full": "assets/instagram/10ba6964bfd55850-1600.webp",
      "width": 600,
      "height": 800,
      "srcWidth": 600,
      "fullWidth": 1200,
      "position": "50% 50%",
      "source": "https://www.instagram.com/aleroblesfotografia/p/DXD4RLXgK7y/",
      "provisional": true,
      "published": true
    }
  ],
  "futureSlots": [
    {
      "id": "nueva-serie-01",
      "title": "",
      "category": "retratos",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-02",
      "title": "",
      "category": "editorial",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-03",
      "title": "",
      "category": "familia",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-04",
      "title": "",
      "category": "exteriores",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-05",
      "title": "",
      "category": "retratos",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    },
    {
      "id": "nueva-serie-06",
      "title": "",
      "category": "editorial",
      "alt": "",
      "src": "",
      "full": "",
      "width": 0,
      "height": 0,
      "position": "50% 50%",
      "source": "",
      "provisional": false,
      "published": false
    }
  ]
};
